#!/usr/bin/env bash
# author: deadc0de6 (https://github.com/deadc0de6)
# Copyright (c) 2021, deadc0de6

set -e

make clean
make
go fmt ./...
golint -set_exit_status ./...
go vet ./...
staticcheck ./...
