settings:
  hosts-parallel: false
  checks-parallel: true
  global-alert:
    type: file
    options:
      path: /tmp/alerts.txt

hosts:
  - name: remote1
    profiles:
      - profile1
    host: 127.0.0.1
    port: '22'
    user: ''
    password: ''
    keyfile: ''
    disable: false
    timeout: '5'
  - name: local
    profiles:
      - profile1
    host: localhost
    disable: false
profiles:
  - name: profile1
    checks:
      - type: disk
        options:
          mount: /
          limit: '80'
      - type: disk
        options:
          mount: /boot
          limit: '90'
      - type: loadavg
        options:
          load_15min: '1'
      - type: process
        options:
          pattern: sshd
      - type: process
        options:
          pattern: firefox
          invert: 'yes'
      - type: memory
        options:
          limit_mem: '90'
          limit_swap: '90'
          limit_total: '90'
      - type: tcp
        options:
          port: '22'
    alerts:
      - type: file
        options:
          path: /tmp/alerts.txt
      - type: webhook
        options:
          url: 'http://127.0.0.1'
          header0: h1
          value0: val1
          header1: h2
          value1: val2
      - type: command
        options:
          command: notify-send
      - type: email
        options:
          host: mail.example.com
          port: '25'
          mailfrom: foo@example.com
          mailto: bar@example.com
          user: username
          password: password
  - name: profile2
    extend: profile1
    checks:
      - type: tcp
        options:
          port: '443'
